description: >
  `stale-md/scan` usage:
usage:
  version: 2.1

orbs:
  stale-md: mkotsollaris/stale-md@0.0.3
  orb-tools: circleci/orb-tools@11.1

jobs:
  scan:
    docker:
      - image: cimg/base:current
    environment:
      IGNORED_FILES: "./.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST.md EXAMPLE.md" # declare files to be ignored during scan
      DAYS_THRESHOLD: 50 # this overrides the default value of 90 days
    steps:
      - checkout
      - stale-md/scan

workflows:
  main:
    jobs:
      - scan